version: "3"
networks:
  loki:
services:
  loki:
    image: grafana/loki:2.4.0
    volumes:
      - ./loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped 
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - loki
    expose:
      - "3100"
  log_creator:
    image: alpine:3.12.4
    container_name: log_creator
    command: >
      sh -c '
          counter=0
          while :
          do
              sleep 1
              echo "{\"message\": \"log line $$counter\", \"something\": \"else\"}"
              counter=$$(($$counter + 1))
          done'
    logging:
      driver: fluentd
  fluentbit:
    image: grafana/fluent-bit-plugin-loki:latest
    ports:
      - "24224:24224/tcp"
      - "24224:24224/udp"
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    restart: unless-stopped
    networks:
      - loki
  grafana:
    image: grafana/grafana:latest
    user: "1000"
    volumes:
    - ./grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - loki
